name: ocr_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_document_scanner: ^0.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  provider: ^6.1.2
  share_plus: ^10.1.4
  permission_handler: ^10.0.0
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
